// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using VocabularyService.Data;

#nullable disable

namespace VocabularyService.Migrations
{
    [DbContext(typeof(VocabularyServiceContext))]
    [Migration("20260520120000_AddReviewLogSnapshotColumns")]
    partial class AddReviewLogSnapshotColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // SQL-only migration; model state is defined in VocabularyServiceContextModelSnapshot.
        }
    }
}
