// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using VocabularyService.Data;

#nullable disable

namespace VocabularyService.Migrations
{
    [DbContext(typeof(VocabularyServiceContext))]
    [Migration("20260514110936_AddAnkiLikeNotes")]
    partial class AddAnkiLikeNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VocabularyService.Data.Entities.AuthorProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Badges")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("badges")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("SocialLinks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("social_links")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("StatsCache")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_cache")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("author_profiles_pkey");

                    b.ToTable("author_profiles", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CardTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_template_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid?>("LemmaId")
                        .HasColumnType("uuid")
                        .HasColumnName("lemma_id");

                    b.Property<string>("Lexicon")
                        .HasColumnType("jsonb")
                        .HasColumnName("lexicon");

                    b.Property<string>("Media")
                        .HasColumnType("jsonb")
                        .HasColumnName("media");

                    b.Property<Guid?>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid?>("ProjectTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_term_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("to_tsvector('english'::regconfig, sentence)", true);

                    b.Property<string>("Sentence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sentence");

                    b.Property<string>("SourceMeta")
                        .HasColumnType("jsonb")
                        .HasColumnName("source_meta");

                    b.Property<string>("Synonyms")
                        .HasColumnType("jsonb")
                        .HasColumnName("synonyms");

                    b.Property<string>("TargetIndex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("target_index")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("TargetWord")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_word");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("cards_pkey");

                    b.HasIndex("CardTemplateId");

                    b.HasIndex("LemmaId");

                    b.HasIndex("NoteId");

                    b.HasIndex("ProjectTermId");

                    b.HasIndex(new[] { "DeckId" }, "idx_cards_deck_id");

                    b.HasIndex(new[] { "SearchVector" }, "idx_cards_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SearchVector" }, "idx_cards_search"), "gin");

                    b.ToTable("cards", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.CardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BackTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("back_template");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FrontTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("front_template");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("NoteTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_type_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("card_templates_pkey");

                    b.HasIndex(new[] { "NoteTypeId", "TemplateKey" }, "ux_card_templates_type_key")
                        .IsUnique();

                    b.ToTable("card_templates", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Contribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("ResolutionComment")
                        .HasColumnType("text")
                        .HasColumnName("resolution_comment");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'::character varying");

                    b.Property<Guid?>("TargetCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_card_id");

                    b.Property<Guid>("TargetDeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_deck_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("contributions_pkey");

                    b.HasIndex("TargetCardId");

                    b.HasIndex(new[] { "AuthorId" }, "idx_contributions_author");

                    b.HasIndex(new[] { "TargetDeckId" }, "idx_contributions_pending")
                        .HasFilter("((status)::text = 'PENDING'::text)");

                    b.ToTable("contributions", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("CardCount")
                        .HasColumnType("integer")
                        .HasColumnName("card_count");

                    b.Property<string>("ContributionPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contribution_policy")
                        .HasDefaultValueSql("'OPEN'::character varying");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ForkedFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("forked_from_id");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_type")
                        .HasDefaultValueSql("'PRIVATE'::character varying");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentDeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_deck_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("decks_pkey");

                    b.HasIndex(new[] { "ParentDeckId" }, "idx_decks_parent_deck_id");

                    b.HasIndex(new[] { "ProjectId" }, "idx_decks_project_id");

                    b.HasIndex(new[] { "IsPublic" }, "idx_decks_public")
                        .HasFilter("(is_public = true)");

                    b.ToTable("decks", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.DeckSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<DateTime>("LastAccessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("LastSyncedVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("last_synced_version");

                    b.Property<DateTime>("SubscribedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscribed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("deck_subscriptions_pkey");

                    b.HasIndex("DeckId");

                    b.HasIndex(new[] { "UserId" }, "idx_subs_user");

                    b.HasIndex(new[] { "UserId", "DeckId" }, "uq_user_deck_sub")
                        .IsUnique();

                    b.ToTable("deck_subscriptions", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.DeckVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("change_description");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by_user_id");

                    b.Property<string>("SnapshotRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("snapshot_ref");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("deck_versions_pkey");

                    b.HasIndex(new[] { "DeckId" }, "idx_deck_versions_deck_id");

                    b.ToTable("deck_versions", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.DeletedObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("DeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("deleted_objects_pkey");

                    b.HasIndex(new[] { "UserId", "DeletedAt" }, "idx_deleted_sync");

                    b.ToTable("deleted_objects", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<string>("FieldValues")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_values")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("NoteTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_type_id");

                    b.Property<Guid?>("ProjectTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_term_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("notes_pkey");

                    b.HasIndex("NoteTypeId");

                    b.HasIndex("ProjectTermId");

                    b.HasIndex(new[] { "DeckId" }, "idx_notes_deck_id");

                    b.ToTable("notes", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.NoteField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_key");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_type");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("NoteTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_type_id");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("note_fields_pkey");

                    b.HasIndex(new[] { "NoteTypeId", "FieldKey" }, "ux_note_fields_type_key")
                        .IsUnique();

                    b.ToTable("note_fields", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.NoteType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Css")
                        .HasColumnType("text")
                        .HasColumnName("css");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("note_types_pkey");

                    b.HasIndex(new[] { "ProjectId", "Name" }, "ux_note_types_project_name")
                        .IsUnique();

                    b.ToTable("note_types", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real")
                        .HasColumnName("average_rating");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .HasDefaultValueSql("'USD'::bpchar")
                        .IsFixedLength();

                    b.Property<string>("DescriptionHtml")
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<Guid>("LinkedDeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_deck_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<int>("SalesCount")
                        .HasColumnType("integer")
                        .HasColumnName("sales_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'DRAFT'::character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex("LinkedDeckId");

                    b.HasIndex(new[] { "AuthorId" }, "idx_products_author");

                    b.HasIndex(new[] { "Status" }, "idx_products_status")
                        .HasFilter("((status)::text = 'PUBLISHED'::text)");

                    b.ToTable("products", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AuthorReply")
                        .HasColumnType("text")
                        .HasColumnName("author_reply");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_verified");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("product_reviews_pkey");

                    b.HasIndex(new[] { "ProductId", "CreatedAt" }, "idx_reviews_product")
                        .IsDescending(false, true);

                    b.ToTable("product_reviews", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FsrsSettings")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("fsrs_settings")
                        .HasDefaultValueSql("'{\"w\": [], \"maximum_interval\": 36500, \"request_retention\": 0.9}'::jsonb");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("SourceLang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("source_lang");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats")
                        .HasDefaultValueSql("'{\"total_lemmas\": 0, \"mature_lemmas\": 0}'::jsonb");

                    b.Property<string>("TargetLang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("target_lang");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("projects_pkey");

                    b.HasIndex(new[] { "UserId" }, "idx_projects_user_id");

                    b.ToTable("projects", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProjectLemma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("MainCardId")
                        .HasColumnType("uuid")
                        .HasColumnName("main_card_id");

                    b.Property<string>("PosTag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pos_tag");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'NEW'::character varying");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("project_lemmas_pkey");

                    b.HasIndex("MainCardId");

                    b.HasIndex(new[] { "ProjectId", "Text" }, "idx_lemmas_text");

                    b.HasIndex(new[] { "ProjectId", "Text", "PosTag" }, "uq_project_lemma")
                        .IsUnique();

                    b.ToTable("project_lemmas", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProjectTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<string>("NormalizedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("project_terms_pkey");

                    b.HasIndex(new[] { "ProjectId", "NormalizedText", "Type" }, "uq_project_terms_norm_type")
                        .IsUnique();

                    b.ToTable("project_terms", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AnswerValidationResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_validation_result");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<float>("DifficultyAfter")
                        .HasColumnType("real")
                        .HasColumnName("difficulty_after");

                    b.Property<float>("DifficultyBefore")
                        .HasColumnType("real")
                        .HasColumnName("difficulty_before");

                    b.Property<DateTime>("DueAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_after");

                    b.Property<DateTime>("DueBefore")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_before");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<int>("ReviewDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("review_duration_ms");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<float>("StabilityAfter")
                        .HasColumnType("real")
                        .HasColumnName("stability_after");

                    b.Property<float>("StabilityBefore")
                        .HasColumnType("real")
                        .HasColumnName("stability_before");

                    b.Property<short>("StateAfter")
                        .HasColumnType("smallint")
                        .HasColumnName("state_after");

                    b.Property<short>("StateBefore")
                        .HasColumnType("smallint")
                        .HasColumnName("state_before");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("text")
                        .HasColumnName("user_answer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("review_logs_pkey");

                    b.HasIndex("CardId");

                    b.HasIndex(new[] { "SessionId", "CreatedAt" }, "idx_logs_session_created")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_logs_user_date");

                    b.ToTable("review_logs", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("CardsReviewed")
                        .HasColumnType("integer")
                        .HasColumnName("cards_reviewed");

                    b.Property<Guid?>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<int>("DurationSec")
                        .HasColumnType("integer")
                        .HasColumnName("duration_sec");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("NewLearned")
                        .HasColumnType("integer")
                        .HasColumnName("new_learned");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'::character varying");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("study_sessions_pkey");

                    b.HasIndex("ProjectId");

                    b.HasIndex(new[] { "UserId", "ProjectId", "EndTime" }, "idx_sessions_heatmap");

                    b.ToTable("study_sessions", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserCardProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<float>("Difficulty")
                        .HasColumnType("real")
                        .HasColumnName("difficulty");

                    b.Property<DateTime>("Due")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due");

                    b.Property<int>("ElapsedDays")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_days");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suspended");

                    b.Property<int>("Lapses")
                        .HasColumnType("integer")
                        .HasColumnName("lapses");

                    b.Property<DateTime>("LastReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_review")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("ScheduledDays")
                        .HasColumnType("integer")
                        .HasColumnName("scheduled_days");

                    b.Property<float>("Stability")
                        .HasColumnType("real")
                        .HasColumnName("stability");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<int>("Step")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("step");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_card_progress_pkey");

                    b.HasIndex("ProjectId");

                    b.HasIndex(new[] { "CardId" }, "idx_progress_card_id");

                    b.HasIndex(new[] { "UserId", "ProjectId", "State", "Due" }, "idx_progress_queue_gen")
                        .HasFilter("(is_suspended = false)");

                    b.ToTable("user_card_progress", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<string>("ExternalOrderId")
                        .HasColumnType("text")
                        .HasColumnName("external_order_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_entitlements_pkey");

                    b.HasIndex("DeckId");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "UserId", "DeckId" }, "idx_entitlements_check")
                        .HasFilter("(is_active = true)");

                    b.ToTable("user_entitlements", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<int>("DailyGoalNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("daily_goal_new");

                    b.Property<int>("DailyGoalReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("daily_goal_review");

                    b.Property<string>("InterfaceLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("interface_language")
                        .HasDefaultValueSql("'en'::character varying");

                    b.Property<DateOnly?>("LastStudyDate")
                        .HasColumnType("date")
                        .HasColumnName("last_study_date");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("integer")
                        .HasColumnName("max_streak");

                    b.Property<int>("RolloverHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("rollover_hour");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId")
                        .HasName("user_settings_pkey");

                    b.ToTable("user_settings", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserTermStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FirstSentence")
                        .HasColumnType("text")
                        .HasColumnName("first_sentence");

                    b.Property<string>("FirstSourceTitle")
                        .HasColumnType("text")
                        .HasColumnName("first_source_title");

                    b.Property<string>("FirstSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("first_source_url");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Meaning")
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ProjectTermId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_term_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_term_statuses_pkey");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectTermId");

                    b.HasIndex(new[] { "UserId", "ProjectTermId" }, "uq_user_term_status")
                        .IsUnique();

                    b.ToTable("user_term_statuses", "internal");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Card", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.CardTemplate", "CardTemplate")
                        .WithMany()
                        .HasForeignKey("CardTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cards_card_templates");

                    b.HasOne("VocabularyService.Data.Entities.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_decks");

                    b.HasOne("VocabularyService.Data.Entities.ProjectLemma", "Lemma")
                        .WithMany("Cards")
                        .HasForeignKey("LemmaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cards_lemmas");

                    b.HasOne("VocabularyService.Data.Entities.Note", "Note")
                        .WithMany("Cards")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cards_notes");

                    b.HasOne("VocabularyService.Data.Entities.ProjectTerm", "ProjectTerm")
                        .WithMany("Cards")
                        .HasForeignKey("ProjectTermId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cards_project_terms");

                    b.Navigation("CardTemplate");

                    b.Navigation("Deck");

                    b.Navigation("Lemma");

                    b.Navigation("Note");

                    b.Navigation("ProjectTerm");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.CardTemplate", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.NoteType", "NoteType")
                        .WithMany("CardTemplates")
                        .HasForeignKey("NoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_templates_note_types");

                    b.Navigation("NoteType");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Contribution", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Card", "TargetCard")
                        .WithMany("Contributions")
                        .HasForeignKey("TargetCardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contributions_cards");

                    b.HasOne("VocabularyService.Data.Entities.Deck", "TargetDeck")
                        .WithMany("Contributions")
                        .HasForeignKey("TargetDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contributions_decks");

                    b.Navigation("TargetCard");

                    b.Navigation("TargetDeck");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Deck", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Deck", "ParentDeck")
                        .WithMany("InverseParentDeck")
                        .HasForeignKey("ParentDeckId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_decks_parent");

                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("Decks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decks_projects");

                    b.Navigation("ParentDeck");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.DeckSubscription", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Deck", "Deck")
                        .WithMany("DeckSubscriptions")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subs_decks");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.DeckVersion", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Deck", "Deck")
                        .WithMany("DeckVersions")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deck_versions_decks");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Note", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Deck", "Deck")
                        .WithMany("Notes")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_decks");

                    b.HasOne("VocabularyService.Data.Entities.NoteType", "NoteType")
                        .WithMany("Notes")
                        .HasForeignKey("NoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_note_types");

                    b.HasOne("VocabularyService.Data.Entities.ProjectTerm", "ProjectTerm")
                        .WithMany()
                        .HasForeignKey("ProjectTermId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notes_project_terms");

                    b.Navigation("Deck");

                    b.Navigation("NoteType");

                    b.Navigation("ProjectTerm");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.NoteField", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.NoteType", "NoteType")
                        .WithMany("NoteFields")
                        .HasForeignKey("NoteTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_fields_note_types");

                    b.Navigation("NoteType");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.NoteType", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("NoteTypes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_note_types_projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Product", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Deck", "LinkedDeck")
                        .WithMany("Products")
                        .HasForeignKey("LinkedDeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_decks");

                    b.Navigation("LinkedDeck");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProductReview", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProjectLemma", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Card", "MainCard")
                        .WithMany("ProjectLemmas")
                        .HasForeignKey("MainCardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lemmas_main_card");

                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("ProjectLemmas")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lemmas_projects");

                    b.Navigation("MainCard");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProjectTerm", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("ProjectTerms")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_terms_projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ReviewLog", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Card", "Card")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logs_cards");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.StudySession", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("StudySessions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserCardProgress", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Card", "Card")
                        .WithMany("UserCardProgresses")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_cards");

                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("UserCardProgresses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_progress_projects");

                    b.Navigation("Card");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserEntitlement", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Deck", "Deck")
                        .WithMany("UserEntitlements")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entitlements_decks");

                    b.HasOne("VocabularyService.Data.Entities.Product", "Product")
                        .WithMany("UserEntitlements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_entitlements_products");

                    b.Navigation("Deck");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.UserTermStatus", b =>
                {
                    b.HasOne("VocabularyService.Data.Entities.Project", "Project")
                        .WithMany("UserTermStatuses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_term_statuses_projects");

                    b.HasOne("VocabularyService.Data.Entities.ProjectTerm", "ProjectTerm")
                        .WithMany("UserTermStatuses")
                        .HasForeignKey("ProjectTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_term_statuses_terms");

                    b.Navigation("Project");

                    b.Navigation("ProjectTerm");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Card", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("ProjectLemmas");

                    b.Navigation("ReviewLogs");

                    b.Navigation("UserCardProgresses");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Deck", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Contributions");

                    b.Navigation("DeckSubscriptions");

                    b.Navigation("DeckVersions");

                    b.Navigation("InverseParentDeck");

                    b.Navigation("Notes");

                    b.Navigation("Products");

                    b.Navigation("UserEntitlements");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Note", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.NoteType", b =>
                {
                    b.Navigation("CardTemplates");

                    b.Navigation("NoteFields");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Product", b =>
                {
                    b.Navigation("ProductReviews");

                    b.Navigation("UserEntitlements");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.Project", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("NoteTypes");

                    b.Navigation("ProjectLemmas");

                    b.Navigation("ProjectTerms");

                    b.Navigation("StudySessions");

                    b.Navigation("UserCardProgresses");

                    b.Navigation("UserTermStatuses");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProjectLemma", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("VocabularyService.Data.Entities.ProjectTerm", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("UserTermStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
